name 'chef_wordpress'
maintainer 'Taylor Monacelli'
maintainer_email 'taylormonacelli@gmail.com'
license 'Apache-2.0'
description 'Installs/Configures chef_wordpress'
long_description 'Installs/Configures chef_wordpress'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)

issues_url 'https://github.com/taylormonacelli/chef_wordpress/issues'
source_url 'https://github.com/taylormonacelli/chef_wordpress'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'

depends 'acme'
depends 'certbot'
depends 'chef_nginx'
depends 'cloudcli'
depends 'cron'
depends 'fail2ban'
depends 'chef_hostname'
depends 'htop'
depends 'mysql'
depends 'php'
depends 'prometheus-platform'
